#!/usr/bin/env bash
# get variables from /etc/lsb-release
source /etc/lsb-release
ARCH=$(dpkg --print-architecture)
MONGO_VERSION="8.0"

if [[   $DISTRIB_CODENAME != 'noble' && \
        $DISTRIB_CODENAME != 'jammy' && \
        $DISTRIB_CODENAME != 'focal' ]]; then
    echo "Wrong Distro or Too Old for MongoDB $MONGO_VERSION: $DISTRIB_CODENAME $DISTRIB_DESCRIPTION"
    exit 1
fi

echo "installing mongodb $MONGO_VERSION public key"
curl -fsSL https://pgp.mongodb.com/server-$MONGO_VERSION.asc \
    | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-$MONGO_VERSION.gpg

echo "Create mongodb list file"
echo "deb [ arch=$ARCH signed-by=/usr/share/keyrings/mongodb-server-$MONGO_VERSION.gpg ] https://repo.mongodb.org/apt/ubuntu $DISTRIB_CODENAME/mongodb-org/$MONGO_VERSION multiverse" \
| sudo tee /etc/apt/sources.list.d/mongodb-org-$MONGO_VERSION.list

sudo apt-get update
sudo apt-get install -y mongodb-org
echo "Installation complete for MongoDB $MONGO_VERSION on $DISTRIB_DESCRIPTION"

